---
apiVersion: v1
kind: Namespace
metadata:
  name: quay-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quay-installer
  namespace: quay-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: quay-installer-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: quay-installer
  namespace: quay-operator
---
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: quay-operator
spec:
  namespace: quay-operator
  serviceAccount:
    name: quay-installer
  source:
    sourceType: Catalog
    catalog:
      packageName: quay-operator
      version: 3.14.3
