---
apiVersion: v1
kind: Namespace
metadata:
  name: operators
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-installer
  namespace: operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-installer-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: operator-installer
  namespace: operators
---
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: quay-operator
spec:
  install:
    preflight:
      crdUpgradeSafety:
        enforcement: None
  namespace: operators
  serviceAccount:
    name: operator-installer
  source:
    sourceType: Catalog
    catalog:
      upgradeConstraintPolicy: CatalogProvided
      packageName: quay-operator
      version: 3.12.7
---
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: kubevirt-hyperconverged
spec:
  install:
    preflight:
      crdUpgradeSafety:
        enforcement: None
  namespace: operators
  serviceAccount:
    name: operator-installer
  source:
    sourceType: Catalog
    catalog:
      upgradeConstraintPolicy: CatalogProvided
      packageName: kubevirt-hyperconverged
      version: 4.16.12
