{{- if .Values.options.operatorController.enabled }}
{{- if (eq .Values.options.featureSet "standard") }}
{{ regexReplaceAll "olm.operatorframework.io([^/])" (tpl (.Files.Get "base/operator-controller/crd/standard/olm.operatorframework.io_clusterextensions.yaml") .) (printf "%s${1}" .Values.apiGroup) }}
{{- else if (eq .Values.options.featureSet "experimental") }}
{{ regexReplaceAll "olm.operatorframework.io([^/])" (tpl (.Files.Get "base/operator-controller/crd/experimental/olm.operatorframework.io_clusterextensions.yaml") .) (printf "%s${1}" .Values.apiGroup) }}
{{- else }}
{{- fail "options.featureSet must be set to one of: {standard,experimental}" }}
{{- end }}
{{- end }}
